create_product_description = {
    'user_prompt': "Write a short, concise description of the product in this image for use as a Google search query. Do not include the brand name.",
    'system_prompt': "Only reply with the asked description text and nothing else!"
}

create_ad_script = {
    "user_prompt": (
        "You are a **top-tier TikTok Ad Scriptwriter**, specializing in **high-converting dropshipping product ads** that grab attention in the first second and maintain sustained attention until the final frame. "
        "Your mission is to write 20-second product ad script for voice over that feels organic, natural, emotionally engaging, and tailor-made for teens on TikTok.\n\n"
        "TikTok is a platform where attention spans are extremely short (1 to 3 seconds to capture interest), and content that evokes strong emotional responses performs best. "
        "Successful TikTok scripts incorporate psychological triggers create a sense of incompleteness that compels viewers to watch until the end. "
        "The most successful videos often utilize pattern interrupts, storytelling frameworks, and strategic calls to action that drive engagement metrics the algorithm rewards.\n\n"
        "**Rules:**\n"
        "- Do NOT include emojis\n"
        "- Do NOT include prefixes like 'Ad script:'\n"
        "- Do NOT include explanations or formatting — just replay with the raw script lines\n"
        '- Avoid using overused marketing clichés such as "everyone has this," "theyre vanishing fast," or similar phrases. These expressions sound generic, salesy, and inauthentic.'
        "- Use simple language\n"
        "- Avoid formal language, technical terms, and brand names\n\n"
        "1. About the product:\n"
        "- **Product**: {product_description}\n"
        "- **Target audience**: Teenagers (short attention spans, used to viral content)\n"
        "- **Key selling angle**: Think of key message or selling point and use it. you can make up a nice story to grab attension\n"
        "- **Ad length**: ~15 seconds\n\n"
        "2. develop a complete TikTok product ad script with these elements:\n\n"
        "1. **Captivating Hook (first 2 to 3 seconds):**\n"
        "- A powerful hook (first 3 seconds) using attention-grabbing techniques\n"
        "- Must stop the scroll. Use pattern interrupts, surprising statements, or emotional triggers.\n"
        "- Evoke shock, or curiosity.\n"
        "- trigger a relatable situation.\n\n"
        "2. **Highlight the Key Features/Benefits (3 to 10 seconds):**\n"
        "- Clearly explain how the product works.\n"
        "- Highlight what it does and why its good.\n"
        "- Use simple, fun language.\n"
        "- Emphasize the biggest benefits for the user.\n"
        "- Can include a creative light story or transformation (for example: \"My mom thought I was cleaning for once... but nah...\")\n\n"
        "3. **Clear Call to Action (CTA):**\n"
        "- Encourage the viewer to take immediate action (e.g., “Click now to get yours”).\n"
        "- End with a strong, fun call to action like:\n"
        "  - “Links in bio”\n"
        "**Tone:**\n"
        "- Straightforward and relatable.\n"
        "- Do not use phrases like “everyone talks about it” or “everyone has this.”\n"
        "- Bold, fast\n"
        "- Avoid anything formal or salesy\n"
        "- Use only very simple English.\n"
        "- Keep it concise and punchy.\n\n"
        "**Important:** The output should be only the text script without anything else — no emojis, no timestamps, no instructions, only the script text.\n\n"
        "**Some exanple outputs:**\n"
        "“I used to spend hours cleaning windows… then THIS happened.”\n"
        "\"This robot sticks to the glass like Spider-Man and cleans every inch while you chill.\"\n"
        "\"No streaks, no ladders, no effort.\"\n"
        "\"Even my mom was shocked how fast it works.\"\n"
        "\"Just stick it on, press go, and boom — clean windows in minutes.\"\n"
        "\"Tap the link and never clean windows again.\""
        "**another exmple output:**\n"
        "\"What happens if it hits the TV?\"\n"
        "\"Guys, please make sure you never hit anything because the spinner will definitely break it.\"\n"
        "\"I'm just kidding...\"\n"
        "\"We designed our spinners to bounce off whatever it hits, so that it always flies back to your hand even if you have a bad throw.\"\n"
        "\"So not only is it super safe, but it's so ridiculously satisfying!\"\n"
        "\"I will leave a link for it in the comments.\""
        "\n"
        "**another exmple output:**\n"
        "\"Here's my honest review of the Sunrise Alarm Clock.\"\n"
        "\"First of all, of course, it's very pretty and very aesthetically pleasing.\"\n"
        "\"The interface is very straightforward and it has a beautifully designed app.\"\n"
        "\"You can select your colors and your sound.\"\n"
        "\"It has many sounds to choose from but nothing beats waking up to waves crashing for me.\"\n"
        "\"You can set up your night routines which helps me go to sleep a lot faster.\"\n"
        "\"I'm very happy with my alarm and it also makes a perfect gift.\"\n"
        "\"I will leave a link for it in the comments.\""
    ),
    "system_prompt": "Only reply with the ad script text. "
        "No emojis, no timestamps, no explanations "
        "Keep it short, bold, fun, and easy to read."
}


create_embeding_prompt = {
    "user_prompt": (
        "Im working with a system that extracts relevant clips from a pool of media using CLIP-based text prompts. "
        "The media pool includes various footage, some of which features our product.\n\n"
        "Generate a focused prompt to retrieve clips that:\n"
        "- Show the unboxing of the product.\n"
        "- Clearly feature our product: {product_description}.\n"
        "- Avoid unrelated items or background distractions.\n"
        "- Are high-resolution and visually clean.\n"
        "- Can work as an attention-grabbing first shot in a promotional video.\n"
        "Do not include any technical details of the product in the prompt."
        "example output:"
        "an image showing unboxing or assembly of a fidget spiral cone toy on  with clear focus on the product; high-resolution, attention-grabbing footage showing interaction for enhanced viewer engagement."
    ),
    "system_prompt": "Only reply with the embedding prompt text — clear, and without technical specifications or brand details."
}


